name: Run E2E Tests
on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  call-run-cy-test:
    name: Test
    uses: ./.github/workflows/cy-tests.yml
    with:
      ref: ${{ github.ref }}
